### ISSUE TITLE
Thanks for this app

### ISSUE THREAD

**Issue by JiLiZART** [jingweno/hacker-menu#24]
Thank you for your application, really cool stuff.

I took it upon myself to make a clone of your application for the Russian analogue of Hacker News http://tmfeed.ru

https://github.com/JiLiZART/tmfeed-menu

I've tested your app on linux, and can make some builds for Ubuntu if you need.

**Comment by jingweno** [comment]
@JiLiZART You're welcome. Thanks for trying it out. Feel free to make a pull request and we can make this app i18n compatible.

**Comment by jingweno** [comment]
I'm closing this. Feel free to add PR to make this app i18n compatible.
